apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-nginx
spec:
  selector:
    matchLabels:
      app: dummy-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: dummy-nginx
    spec:
      containers:
        - name: dummy-nginx
          image: dummy-nginx:1.0
          ports:
            - containerPort: 80
