---
- name: update apt and install required tools
  apt:
    pkg:
      - apt-transport-https
      - curl
    state: present
    update_cache: true
- name: add k8s repos to apt
  ansible.builtin.shell: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  become: yes
- name: update once again apt with the new repos and install kubelet kubeadm
  apt:
    pkg:
      - kubelet
      - kubeadm
    update_cache: true


On master node:
- enable and start kubelet: `systemctl enable kubelet && systemctl start kubelet`,
- enable and start docker: `systemctl enable docker && systemctl start docker`,
- disable swap before install kubeadm: `swapoff -a`,
- create cluster: `kubeadm init`. It will do a lot of things,
At the end of init process, kubeadm will tell which command to run:
- `mkdir -p $HOME/.kube`,
- `sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config`,
- `sudo chown $(id -u):$(id -g) $HOME/.kube/config`.

More important: kubeadm will tell which command to run to join nodes to the cluster:
- `kubeadm join masternode.ip:masternode.port --token some.weird.symbols.sequence.as.token --discovery-token-ca-cert-hash a.more.weird.symbols.sequence.as.token`
Now I have to deploy a basic startup items on cluster:
- `kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=k8s.version.of.choice"`. This will deploy a network and a lot more.
