---
- hosts: rpi.k8s.node
  vars:
    k8s_version: 1.20
  tasks:
    - name: check if docker is already installed, if so docker_is_installed will be valued to 0
      shell: command -v docker
      register: docker_is_installed
      check_mode: no
    - name: install docker
      include_role:
        name: docker.install
      when: docker_is_installed.stdout != "/usr/bin/docker"
    - name: configure docker
      include_role:
        name: docker.configure
    - name: install and configure k8s as generic node (worker)
      include_role:
        name: simple.node
- hosts: rpi.k8s.master
  roles:
    - master.node
- hosts: rpi.k8s.node
  tasks:
    - name: check a cni is already installed
      raw: test -e /etc/cni/net.d && echo true || echo false
      register: cni_is_installed
      check_mode: no
    - name: install calico if no cni is already installed
      include_role:
        name: calico.install
      when: cni_is_installed != true
