---
- name: check if docker is already installed
  command: docker
  register: docker_is_installed
  ignore_errors: true
- name: download docker install script from get.docker.com
  ansible.builtin.get_url:
    url: http://get.docker.com
    dest: /tmp/get-docker.sh
  when: docker_is_installed.rc != 1
- name: Changing perm of "/tmp/get-docker.sh", adding "+x"
  ansible.builtin.file:
    path: /tmp/get-docker.sh
    mode: '1777'
  when: docker_is_installed.rc != 1
- name: run docker install script
  ansible.builtin.shell: /tmp/get-docker.sh
  when: docker_is_installed.rc != 1
- name: Create docker group
  group:
    name: "docker"
    state: present
  become: yes
  when: docker_is_installed.rc != 1
- name: Add user 'pi' to docker group
  user:
    name: "pi"
    groups: "docker"
    append: "yes"
  become: yes
  when: docker_is_installed.rc != 1
- name: install pip3 because of docker-compose
  apt:
    name: python3-pip
  become: yes
  when: docker_is_installed.rc != 1
- name: install docker-compose
  ansible.builtin.shell: pip3 install docker-compose
  become: yes
  when: docker_is_installed.rc != 1
- name: check docker is installed correctly
  ansible.builtin.shell: docker run hello-world
